### ISSUE TITLE
Android build (pre-lollipop) has no control overlay

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#1]
I don't know if it's a bug related to my device, or if it's just that the feature hasn't been implemented, but there is absolutely no controls indication on my phone (HTC Desire 620) when playing the latest pre-lollipop android builds. On the other hand, it does seem that there are touch controls designed to play as if the device was a gamepad (i.e. directional pad on the left, confirmation key on the right, etc.).

Currently I have to guess the position of all controls, which is not so easy.

**Comment by trentg** [comment]
The game is designed to turn off the touch control display if a joystick is detected. I'm guessing it thinks you have one. Do you have anything that may be confused with a joystick? Joystick driver, Bluetooth device or anything like that?

**Comment by akien-mga** [comment]
I don't have any joystick nor anything that I can think of that could be confused with a joystick. At first I was taking while the device was connected to my laptop with a USB cable, so I unplugged it to be sure. I also made sure all external connection interfaces were turned off (bluetooth, wifi, mobile data). Would I get some interesting log output if I debugged with adb logcat?

**Comment by akien-mga** [comment]
The device uses Android 4.4.4 and an input overlay called HTC Sense 6.0; the latter might be the culprit, I'll see if I can disable it.

**Comment by trentg** [comment]
First off, this is an Allegro bug, but I wrote that code so I'll try to fix it. :P

Can you test a build for me if I upload it somewhere?

**Comment by akien-mga** [comment]
> Can you test a build for me if I upload it somewhere?

Sure :)

**Comment by trentg** [comment]
DM'ed you a link, thanks.

**Comment by akien-mga** [comment]
I tried it, but it doesn't solve the issue sadly :/

Another thing, the 1.7 apk was not recognised as an update of the 1.6 version, so I ended up with two versions installed at first (and not having the 1.6 user data in the new version, though my save was only past the intro ;)).

**Comment by trentg** [comment]
Uploaded another to the same location if you have time. This one has the same package name as 1.6 and will be an upgrade. The check for gamepads has been changed to check for gamepads *WITH BUTTONS* which has been known to help before, though I can only guess if it will in this case.

**Comment by akien-mga** [comment]
I rolled back to 1.6 to confirm that the new apk is seen as an update, that works great :)
On the other hand, still no luck with the controls :-/ I'll see if I find something useful in the logs.

**Comment by akien-mga** [comment]
I found this in the logs:
```
D/AllegroActivity(15164): Number of input devices: 7
D/AllegroActivity(15164): Found joystick. Index=0 id=2
```
7 input devices! :)

**Comment by trentg** [comment]
It's not unusual to have lots of input devices, but it shouldn't be thinking that one is a joystick if it isn't. Problem is, we're using the Google-recommended method of detecting a joystick which is:

    private boolean isJoystick(int id) {
         InputDevice input = InputDevice.getDevice(id);
         int sources = input.getSources();
         if ((sources & InputDevice.SOURCE_GAMEPAD) == InputDevice.SOURCE_GAMEPAD || (sources & InputDevice.SOURCE_JOYSTICK) == InputDevice.SOURCE_JOYSTICK) {
            return true;
         }
         return false;
    }

Prior to the first APK I got you to test, this was using the NVIDIA-recommended method which probably amounts to the same thing, but is slightly different...

There must be a way around this, I'll have to do some Googling to see if anyone has come up with a solution. Thanks!

**Comment by trentg** [comment]
Looks like SDL only checks for SOURCE_JOYSTICK, not GAMEPAD... I can try another APK like that if you're willing, but I'll have to verify it myself on a few devices to make sure it doesn't break something else.

**Comment by akien-mga** [comment]
Sure, I can give it a try.

**Comment by trentg** [comment]
Same location. Thanks.

**Comment by akien-mga** [comment]
It works! \o/

**Comment by trentg** [comment]
Nice. Highly appreciate your testing and reporting, thank you. I want to try it on one more device (Fire TV) and then I'll upload it into production.
