### ISSUE TITLE
Minor issue in the settings UI

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#12]
I just stumbled upon a minor bug in the settings UI. Under some circumstances that I haven't precisely determined yet, going up (with the Up key on a desktop platform) from the "Return" button skips the "Language" entry and goes directly to "Configure the gamepad". Then going down goes to "Language" as expected.

**Comment by trentg** [comment]
Which version is this with?

**Comment by akien-mga** [comment]
With the preview of 1.8. It's not easy to reproduce, you need to play around with parameters like changing languages several times, going back to the title screen, then again in settings... I'm trying to see if I find a clear procedure to reproduce the issue.

**Comment by trentg** [comment]
Ah, I know why, and it happens every time for me with French selected. The GUI system automatically jumps to the next "up" widget, but "Language" is not directly up from it, so it misses it.

**Comment by akien-mga** [comment]
Ok I found one way to reproduce the issue, it might be related to my translation somehow:
* Start the game in English, no issue.
* Change the language to French.
* Go back to the title screen
* Go to the settings menu, the issue should be there

**Comment by akien-mga** [comment]
Ah right, "Langue" is too short :-D

**Comment by trentg** [comment]
If the language text were longer it would hit it... let me see if I can set the size of the widget manually.

**Comment by akien-mga** [comment]
So it can be reproduced with German too, "Sprache" is too short.

**Comment by akien-mga** [comment]
Another possibility if you don't want to hack the widgets would be to make the entries shorter, and center them above the Return button. Like:
* Audio Options
* Video Options
* Keyboard
* Gamepad
* Language

(So basically drop the "Configure" work in the first four entries)

**Comment by trentg** [comment]
Do you know German well enough to translate those ones?

**Comment by akien-mga** [comment]
Sure, my daytime work is in German (since two weeks alright, but still ;-))

**Comment by trentg** [comment]
Ok, waiting for a patch then. :)

**Comment by akien-mga** [comment]
Speaking about too long strings, I just started a game in German and I notice that most names are too long for the UI. I'll see if I can fix some of them without losing important meaning.

**Comment by akien-mga** [comment]
Actually this issue is fixed already as the position of the widgets is calculated based on the length of the longer one, so with short strings, everything is ok.
