### ISSUE TITLE
Diagonal movement a tad slow on desktop

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#3]
The moving speed intensity is very well handled on android, I like how it emulates a digital joystick.

On desktop however, I find that the diagonal movement is pretty slow compared to the horizontal and vertical movement (at least when walking, but to some extent also when running). It feels almost as if it takes the same time to go from one point to another by taking the shortest diagonal path or by going horizontally and then vertically.

**Comment by akien-mga** [comment]
Note that I haven't checked the code, this might very well be a misleading impression :)

**Comment by trentg** [comment]
It could be possible, however remember that travelling diagonally covers more distance so it should appear slightly slower. Example, on horizontal if you do x += 1; each frame, then diagonal should not be x += 1, y += 1 but x += 0.707, y += 0.707... I think this is what the code does but I'd have to double check.

**Comment by akien-mga** [comment]
Yeah that's what I would expect the code to do too, therefore I'm thinking it might just be a trick that my mind plays me :)

**Comment by trentg** [comment]
I'll check it out and make sure.

**Comment by trentg** [comment]
Looks like this is what the code is doing. See player.cpp:186.

**Comment by akien-mga** [comment]
Indeed the code looks good :)
