### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#4]
The dialogues in this game are too funny to leave my fellow non-English speaking Frenchmen bereft of enjoying them, so I think I'll work on a French translation while playing through the game myself.

*Edit:* s/Frenchmen/French speakers/, I should remember I'm writing to a Canadian citizen :-D

Just opening this ticket as a heads up (and so that other potential translators know about it in case it takes me months to complete ;)).

**Comment by akien-mga** [comment]
As for the technical aspects I think it's pretty simple how the translation should be handled and fed to the engine; I'll just have to find out how to build the game myself to take into account my changes to src/language_config_loop.cpp (though I could just override German.utf8 locally to test my changes in-game).

**Comment by trentg** [comment]
Sounds great! Building the game is not streamlined unfortunately. If you need help, let me know. We can fix any issues along the way.

**Comment by akien-mga** [comment]
Thanks for the translation-enabled binary, it works great.

One question about the dialogues: how formal are the various NPCs when talking to the heroes? In French we have both an informal (« tu ») and formal (« vous ») 2nd person pronoun to translate "you". So far I've been using the formal form, but I see that the German translation uses mostly „du“, so the informal pronoun.

An underlying question is how close the protagonists and the NPCs are to each other. If they all grew up in River Town which is a small city, it's pretty safe to assume that they are acquaintances and would use the informal pronoun. Basically in French the formal form is used when addressing people that you don't know, or when there is a clear hierarchical difference.

**Comment by trentg** [comment]
I think you should use informal because the protagonists live in River Town (if you're clever you can find their homes.)

**Comment by akien-mga** [comment]
Yeah I'm in Frogbert's house right now ;) I'll go with informal then. Singular or plural?

**Comment by trentg** [comment]
I would say plural though my French c'est nes pas tres bien. :P

**Comment by akien-mga** [comment]
;-) Ok thanks, I'll go with plural apart from when the context is pretty clear (like the NPC who tells one of the two characters that their hair is terrible, or the NPC that talks directly to Frogbert about the seeds he ordered, etc.)

**Comment by trentg** [comment]
Sounds good!

**Comment by akien-mga** [comment]
I'm making good progress, I guess I'm halfway through: https://github.com/akien-mga/crystal-picnic/tree/french

Two questions:
* There are two NPCs who say "Ants did this? Doubtful. They're not known for tunnelling. Or am I thinking of eagles?", namely PIG_CRYSTAL_4_2 and FOX_BANQUET_2. Is that intended?
* What is meant by "Arrange Up" and "Arrange Down" in the gamepad bindings configuration screen?

**Comment by trentg** [comment]
1) No, not intended. The fox is not supposed to say that, and in fact never does so FOX_BANQUET_2 should be removed.

2) Arrange up and down lets you arrange your items. If you open your item screen and select an item, pressing pgup/pgdn will move it up/down in the list.

**Comment by trentg** [comment]
Going to remove FOX_BANQUET_2 from git, thanks.

**Comment by akien-mga** [comment]
Translation of the description from https://nooskewl.ca/crystal-picnic/

----------

Crystal Picnic est un hommage haut en couleur et bon enfant à l'époque classique des action-RPG ! Rejoignez un jardinier sarcastique et un aspirant chevalier dans leur voyage à travers le royaume, à la poursuite de fourmis qui ont volé les cristaux magiques du château. Oh, et est-ce qu'on vous a dit que ces fourmis sont devenues tarées après avoir MANGÉ ces cristaux ? Ouais, ça rend les choses beaucoup moins prévisibles ! Des heures d'exploration, de combat hypnotisant type jeu de plateforme, de nombreux nouveaux amis à rencontrer et des tas d'ennemis farfelus à confronter. Lorsque vous avez à combattre des oiseaux bien en chair et des fourmis armées de bazookas, vous savez d'ores et déjà que vous allez passer un bon moment !

Parmi les caractéristiques sympa de ce jeu :
- Combats en temps réel
- De nombreux éléments de jeu de rôle (équipement, compétences, etc.)
- Une histoire pleine d'humour dans un univers original
- Du pixel-art de qualité
- D'excellentes musiques rétro
- Un téléchargement léger

Jouable en français, anglais et allemand.

----------

**Comment by akien-mga** [comment]
I'm not sure I understand those three strings, and I haven't seen then in game: https://github.com/Nooskewl/crystal-picnic/blob/master/data/text/English.utf8#L132-L134

Are they used, and if so could you give me some context?

**Comment by trentg** [comment]
They're used for arrow upgrades which you can find in a couple levels.

**Comment by akien-mga** [comment]
Ah right, thanks.

**Comment by akien-mga** [comment]
> They're used for arrow upgrades which you can find in a couple levels.

How are they used though? I found Iron Arrows, but when I click them in the Equip screen of Bisou, they are automatically equipped. If I click them in the Equip screen of another character, they are greyed out and therefore nothing happens.

**Comment by akien-mga** [comment]
Maybe I missed other arrow upgrades that would trigger this mechanism though.

**Comment by trentg** [comment]
They're probably just there for completeness. I made attachments generic enough to be used for any weapon, just only used it for arrows.

**Comment by akien-mga** [comment]
Ok, that makes sense. The engine indeeds seems to have a lot of potential for a sequel or a longer game... :-D

**Comment by trentg** [comment]
Ok, if the translation is 100%, I will get to releasing 1.8 right away. Thanks!

**Comment by akien-mga** [comment]
Yep, the version in my pull request is 100% done. It might still use a full playthrough to get some proofreading, but I'll try to find some friend or relative to buy the game and do the proofreading for me :p

**Comment by Bertram25** [comment]
>  but I'll try to find some friend or relative to buy the game and do the proofreading for me :p

As I've already bought the game, I'll gladly do it if you're ok with it. ;)
@akien-mga Thanks for the French translation!
@trentg Thanks a lot for the game. :)

**Comment by akien-mga** [comment]
@Bertram25 Awesome, I was about to tell you about @trentg's awesome games and how you might be interested in following the development of Monster RPG 3 ;)

@trentg @Bertram25 here is a fellow developer of @OpenDungeons, and also the main dev of Valyria Tear, which is a pretty rad libre JRPG :)

**Comment by trentg** [comment]
Hi @Bertram25! You can get my email address from @akien-mga and I'll send you a link to 1.8 which is final except for one small bugfix I need to make.

**Comment by Bertram25** [comment]
> you might be interested in following the development of Monster RPG 3 ;)

WHAT!? Totally!!

> Hi @Bertram25! You can get my email address from @akien-mga and I'll send you a link to 1.8 which is final except for one small bugfix I need to make.
 
Thanks a lot @trentg :) I'll wait for the 1.8 to be final, and have a new game, then. :)
