### ISSUE TITLE
Item descriptions get mixed up in equip screen after equiping one item

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#7]
I will send you a saved state that exhibits the problem.
Go to the equip screen for Frogbert: he wears a Hockey Mask (the description says "+2 Defense" and is accurate), and there are Garden Gloves available (the description says "+2 Attack", also accurate).

Then if you equip the Garden Gloves, and click the information button to read descriptions, you'll see that both items now say "+2 Attack". Swap again, then both say "+2 Defense", etc.

**Comment by trentg** [comment]
Ack, I need to fix this before 1.8, so the link I gave you is not final.

**Comment by trentg** [comment]
Cannot find this save state in my email. Do you still have it?

**Comment by akien-mga** [comment]
I just resent your the email.

**Comment by trentg** [comment]
Got it, thank you.
