### ISSUE TITLE
Stuck at Stone Crater because I don't know how to "Jump"

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#8]
In the "Stone Crater 2" level, the player is supposed to "Jump" over a chasm; but there is no event triggered to teach me how to do this.

So either the missing event is a bug, or the player is supposed to have learned this skill before. The only other place where I encountered a "Jump" sign is at the Intersection, without being able to access it. Did I miss something, or is it a bug?

**Comment by trentg** [comment]
This is a bug that was fixed in 1.7, I presume you're using the 1.6 binary? In 1.7 you cannot go backwards, you must go through the anthill... it's an unfortunate bug but it's fixed in 1.7.

**Comment by akien-mga** [comment]
Ah I see, it makes sense. I guess I'll have to finish my translation quickly and wait for 1.8 to finish the game then, since I can't save with 1.7 ;)

Or can I add something in boss.lua or a save*.lua that would make as if I had learned to jump?

**Comment by akien-mga** [comment]
Ok I've found that I need to add:
```set_milestone_complete("jump_switch_info", true)```

Your save format is very simple but quite clever I find :)

**Comment by trentg** [comment]
They are actually Lua code, so you can do all kinds of things in there... :P
