### ISSUE TITLE
Suggestion: increase difficulty of the chest puzzle

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/crystal-picnic#9]
The chest puzzle uses a pretty classic mechanism, but I wonder if it should not be made a little bit more difficult, maybe by making it a code of 4 or 5 digits instead of 3.

It would not require adding more chests, which would be somewhat boring IMO, but maybe just make a longer combination, like: Middle - Right - Left - Left - Middle.

Just a random idea, if you think it wouldn't add much interest to the puzzle, feel free to discard it :)

**Comment by trentg** [comment]
Won't do this on design principles.

**Comment by akien-mga** [comment]
Fine by me :)
